apiVersion: v1
kind: Service
metadata:
  name: payments-service
  labels:
    app: payments
spec:
  type: ClusterIP
  selector:
    app: payments
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
