apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers-deployment
  labels:
    app: customers
spec:
  replicas: 4
  selector:
    matchLabels:
      app: customers
  template:
    metadata:
      labels:
        app: customers
    spec:
      containers:
      - name: customers
        image: customers:latest
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: postgres-creds-cust
