apiVersion: v1
kind: Service
metadata:
  name: customers-service
  labels:
    app: customers
spec:
  type: ClusterIP
  selector:
    app: customers
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
