apiVersion: apps/v1
kind: Deployment
metadata:
  name: pricing-deployment
  labels:
    app: pricing
spec:
  replicas: 6
  selector:
    matchLabels:
      app: pricing
  template:
    metadata:
      labels:
        app: pricing
    spec:
      containers:
      - name: pricing
        image: pricing:latest
        ports:
        - containerPort: 80
