apiVersion: v1
kind: Service
metadata:
  name: pricing-service
  labels:
    app: pricing
spec:
  type: ClusterIP
  selector:
    app: pricing
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
